name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    name: Build & Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup MoonBit Toolchain (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libssl-dev
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> "$GITHUB_PATH"

      - name: Setup MoonBit Toolchain (macOS)
        if: runner.os == 'macOS'
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> "$GITHUB_PATH"

      - name: Setup MoonBit Toolchain (Windows)
        if: runner.os == 'Windows'
        run: |
          powershell -Command "iwr https://cli.moonbitlang.com/install/powershell.ps1 -useb | iex"
          echo "$HOME/.moon/bin" >> "$GITHUB_PATH"

      - name: MoonBit Type Check
        run: moon check

      - name: MoonBit Run Tests
        run: moon test

      - name: MoonBit Source Code Formatting Check
        run: moon fmt

      - name: MoonBit Interface Generation Check
        run: moon info
